enviroment_eav_homepage:
    path:     /
    defaults: { _controller: "EnviromentEavBundle:Schema:index" }

enviroment_eav_new:
    path:     /new/{id}
    defaults: { _controller: "EnviromentEavBundle:Schema:new" }
    options:
        expose: true

enviroment_eav_edit:
    path:     /edit/{id}
    defaults: { _controller: "EnviromentEavBundle:Schema:edit" }
    options:
        expose: true

enviroment_eav_delete:
    path:     /delete/{id}
    defaults: { _controller: "EnviromentEavBundle:Schema:delete" }
    methods:  [POST, DELETE, GET]
    options:
        expose: true

enviroment_eav_difinitions:
    path:     /difinitions/{id}
    defaults: { _controller: "EnviromentEavBundle:Schema:difinitions" }
    options:
        expose: true